#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-RAI
version:      0.52
version_from: lib/XML/RAI.pm
installdirs:  site
requires:
    Date::Parse:                   0
    XML::RSS::Parser:              2.1
    POSIX:                         0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
