#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-RAI
version:      1.301
version_from: lib/XML/RAI.pm
installdirs:  site
requires:
    Date::Parse:                   2.26
    File::Spec:                    0
    Test::More:                    0
    XML::RSS::Parser:              4
    Date::Format:                  2.22

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
