#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-RAI
version:      1.3
version_from: lib/XML/RAI.pm
installdirs:  site
requires:
    Test::More:                    0
    Date::Parse:                   2.26
    Date::Format:                  2.22
    XML::Elemental:                1.01
    File::Spec:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
