#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-RAI
version:      0.3
version_from: lib/XML/RAI.pm
installdirs:  site
requires:
    XML::RSS::Parser:              2.1
    POSIX:                         Date::Parse

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
